"""
HTTP server that runs on a background daemon thread inside Fusion.
Receives commands from the MCP server, queues them for the main thread,
and returns results.
"""

import http.server
import json
import threading
import traceback

# These will be set by start_server()
_auth_token = None
_custom_event_id = None


class BridgeRequestHandler(http.server.BaseHTTPRequestHandler):
    """Handle incoming HTTP POST requests from the MCP server."""

    # Suppress default stderr logging (it clutters Fusion's console)
    def log_message(self, format, *args):
        pass

    def do_POST(self):
        # -- Authenticate --
        auth_header = self.headers.get('Authorization', '')
        if auth_header != f'Bearer {_auth_token}':
            self.send_response(401)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': 'Unauthorized: invalid or missing Bearer token'
            }).encode())
            return

        # -- Read and parse body --
        try:
            content_length = int(self.headers.get('Content-Length', 0))
            body = self.rfile.read(content_length)
            payload = json.loads(body)
        except Exception as e:
            self.send_response(400)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': f'Bad request: {str(e)}'
            }).encode())
            return

        # -- Dispatch to the appropriate handler --
        try:
            operation = payload.get('operation', '')

            if operation == 'ping':
                # Health check -- does not need the main thread
                import fusion_bridge
                result = {'success': True, 'result': 'pong',
                          'version': fusion_bridge.__version__}

            elif operation in ('api_call', 'python_exec', 'inspect',
                               'pin_document', 'unpin_document', 'pin_status',
                               'capture_viewport'):
                # These MUST run on Fusion's main thread via CustomEvent
                import api_executor
                result = api_executor.execute_on_main_thread(
                    operation, payload, timeout=30
                )

            else:
                result = {
                    'success': False,
                    'error': f'Unknown operation: {operation}'
                }

            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps(result).encode())

        except Exception as e:
            self.send_response(500)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': str(e),
                'traceback': traceback.format_exc()
            }).encode())

    def do_GET(self):
        """Reject GET requests with a helpful message."""
        self.send_response(405)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({
            'success': False,
            'error': 'Only POST requests are accepted'
        }).encode())


def start_server(host, port, token, stop_event, custom_event_id):
    """
    Start the HTTP server. Called from a background daemon thread.
    Blocks until stop_event is set.

    Args:
        host: Bind address (must be '127.0.0.1')
        port: Port number (default 45876)
        token: Bearer auth token (generated by fusion_bridge.py)
        stop_event: threading.Event that signals shutdown
        custom_event_id: Fusion CustomEvent ID string
    """
    global _auth_token, _custom_event_id
    _auth_token = token
    _custom_event_id = custom_event_id

    server = http.server.HTTPServer((host, port), BridgeRequestHandler)
    server.timeout = 1.0  # Check stop_event every second

    while not stop_event.is_set():
        server.handle_request()

    server.server_close()
